### PR TITLE
The default buffer size of 0 usually isn't enough

### PR DESCRIPTION
**Pull request by Blacksilver42**
At least not for my setup. Serial output gets cut off.

### CODE REVIEW

**Comment by Blacksilver42** [comment]
```
ing Zephyr OS build zeph90f4c3 *****
[00:00:00.004,974] <inf> mcuboot: Startng bootloader
n_type=0x1, copy_done=0x3, image_ok=0x3
[00:00:00.021,270] <inf> mcuboot: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
[00:00:00.030,609] <inf> mcuboot: Boot source: primary slot
[00:00:00.039,611] <inf> mcuboot: Swap type: none
[00:00:00.044,738] <err> mcuboot: Unable to find bootable im
```
(no more ouput)
\* flashes fixed version *
```
***** Booting Zephyr OS build zephyr-v1.14.0-2240-g4ca54390f4c3 *****
[00:00:00.004,943] <inf> mcuboot: Starting bootloader
[00:00:00.011,383] <inf> mcuboot: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
[00:00:00.021,240] <inf> mcuboot: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
[00:00:00.030,578] <inf> mcuboot: Boot source: primary slot
[00:00:00.039,581] <inf> mcuboot: Swap type: none
[00:00:00.044,708] <err> mcuboot: Unable to find bootable image
```

**Comment by nvlsianpu** [comment]
Zephyr defines this configuration in range for <128, 65536>. something is bad with the setup on which problem with 0 size occurred.

This patch fix symptoms of setup problem someone have.

**Comment by Blacksilver42** [comment]
Don't have to set it to 128, that number is arbitrary.

... So it's the board's fault or something?

**Comment by d3zd3z** [comment]
I wonder if this is related to the problem where we don't wait for the uart to drain before either starting the next image or halting on failure.

**Comment by nvlsianpu** [comment]
@Blacksilver42 With zephyr mainline it is not possible to even compile with smaller size (build will fail on Kconfig). What a version did you use?

**Comment by Blacksilver42** [comment]
@nvlsianpu The latest version straight from their github: https://github.com/zephyrproject-rtos/zephyr. I downloaded using West.

**Comment by Blacksilver42** [comment]
> On smaller sizes it still happens sometimes.

What idiot wrote that sentence?

It still happens occasionally on 128, which is the minimum valid size -- just a lot less.

**Comment by Blacksilver42** [comment]
* Realizes it's impossible to set to zero *

Welp!

**Pull request closed without merging**
