### PR TITLE
boot: zephyr: migrate to new log subystem

### PR DESCRIPTION
**Pull request by lemrey**
The old log subsystem has been deprecated in Zephyr.
Migrate to the new subsystem to avoid compilation warnings.

@nvlsianpu I might have missed something, please have a look.

### CODE REVIEW

**Comment by utzig** [comment]
I am not aware of those Zephyr changes, but does it really need to be registered in every single file? Wouldn't registering in `main.c` be enough?

**Comment by nvlsianpu** [comment]
@lemrey Did you test this PR? - I can't get any logg using it.

**Comment by lemrey** [comment]
@nvlsianpu I tested that it compiled without warnings, I did not try to run it.

**Comment by lemrey** [comment]
@nvlsianpu what issue did you see? I might have some time to look at this now.

**Comment by nvlsianpu** [comment]
^^ @lemrey updates are welcome

**Comment by d3zd3z** [comment]
> If the module consists of multiple files, then `LOG_MODULE_REGISTER()` should
appear in exactly one of them.

I'm pretty sure we should be using `LOG_MODULE_REGISTER()` in exactly one place, and `LOG_MODULE_DECLARE()` in the other files.

**Comment by nvlsianpu** [comment]
In-place log processing is selected as it is required as MCUBoot is
one thread application. Now it works properly.

**Comment by d3zd3z** [comment]
The new version still should be calling `LOG_MODULE_REGISTER` in only one place, and `LOG_MODULE_DECLARE` in the other files.

**Comment by nvlsianpu** [comment]
@d3zd3z -  Your remarks were taken into account. This implies registration one log-module for entire mcuboot (versus multiple log-modules previously).

**Comment by nvlsianpu** [comment]
@utzig CI passed, while is not visible here - strange is it.

**Comment by utzig** [comment]
@nvlsianpu Re-run CI and it's in sync again.

**Comment by lemrey** [comment]
Hi @utzig, thank you for reviewing.
I should have addressed your comment.

**Comment by utzig** [comment]
@lemrey Seems to be missing the macros in `sim/mcuboot-sys/csupport/mcuboot_config/mcuboot_logging.h`

**Comment by lemrey** [comment]
@utzig thank you :)

**Pull request merged**
