### PR TITLE
sim: add bootstrap test

### LINKED ISSUE #706: Bootstrap does not work when CONFIG_BOOT_SWAP_USING_MOVE=y
I am trying to bootstrap MCUBoot using Slot1 but it does not seem to work when CONFIG_BOOT_SWAP_USING_MOVE=y. 

It seems like it fails on checking the magic for Slot 0. This is expected as there is nothing in Slot0 but I do not understand why it is checked.

Is this a bug in MCUBoot or have I misunderstood how this is supposed to work?
It works fine when CONFIG_BOOT_SWAP_USING_MOVE=n

RTOS: Zephyr
Target board: particle_boron
mcuboot conf:
```
CONFIG_BOOT_BOOTSTRAP=y
CONFIG_BOOT_SWAP_USING_MOVE=y
```

### PR DESCRIPTION
**Pull request by utzig**
This should fix bootstrap in swap-move along with other fixes.

@d3zd3z After some issues I've found working on this PR, I think we should just remove the `MCUBOOT_OVERWRITE_ONLY_FAST` option and make it the default behavior when doing overwrite-only, what do you think?

Fixes #706, #738

### CODE REVIEW

**Review by d3zd3z — APPROVED** [review]

**Comment by erik-johnson-nimbelink** [comment]
I don't think commit 738c8b7 is quite right. If I'm not mistaken, "BOOT_CURR_IMG(state)" doesn't mean primary/secondary, but rather which image is being checked. So, if trying to bootstrap an image that isn't the first one -- which I happen to be currently doing -- this will fail. Removing that check lets me bootstrap my second image.

Wouldn't it be sufficient to only have the erased header check there?

**Comment by utzig** [comment]
> Wouldn't it be sufficient to only have the erased header check there?

Yes I agree, it was a mess-up on my part, I think it's safe to remove the check you mentioned. Have you tried bootstrapping a multi-image test in the simulator?

**Comment by erik-johnson-nimbelink** [comment]
I haven't used the simulator, and we're behind quite a bit from master since we're close to release. But, for what it's worth, I did try a series of real-world tests, and removing the check did allow me to bootstrap the primary slot in my second image.

**Comment by utzig** [comment]
> I haven't used the simulator, and we're behind quite a bit from master since we're close to release. But, for what it's worth, I did try a series of real-world tests, and removing the check did allow me to bootstrap the primary slot in my second image.

Ok, what MCU did you use for testing? Please send a PR.

**Pull request merged**
