### PR TITLE
Remove bootutil unit test for Mynewt

### PR DESCRIPTION
**Pull request by sjanc**
mcuboot tests are done under sim and there is no need to maintain
separate tests just for Mynewt. Especially that those no longer
compile nor are maintained.

Also Mynewt code will rather depend on release and not master so
there is no need to run those on Mynewt anyway.

### CODE REVIEW

**Comment by sjanc** [comment]
@utzig @ccollins476ad

**Comment by utzig** [comment]
Ain't you removing a bit too much? (e.g `boot/bootutil/include/bootutil/bootutil.h`)

**Comment by utzig** [comment]
I think you should only remove stuff under `boot/bootutil/test/` tree, no?

**Comment by utzig** [comment]
LGTM, any thoughts @ccollins476ad?

**Comment by sjanc** [comment]
those tests are non functional and not used anyway... can we just remove them?

**Comment by sjanc** [comment]
I mean, if someone ever needs them can restore and fix..  it is all in git history

**Pull request merged**
