### PR TITLE
zephyr: cmake: Remove obsolete code

### PR DESCRIPTION
**Pull request by ChristopherBittner**
set_conf is not used anymore.
This functionality was replaced.

Signed-off-by: Chris Bittner <chris.bittner@nordicsemi.no>

### CODE REVIEW

**Comment by utzig** [comment]
@SebastianBoe @lemrey opinions?

**Comment by ChristopherBittner** [comment]
cc @SebastianBoe

**Comment by SebastianBoe** [comment]
I can confirm that set_conf_file should be removed.

The pattern it is implementing was adopted by the core build scripts:
https://github.com/zephyrproject-rtos/zephyr/blob/master/cmake/app/boilerplate.cmake#L350

**Comment by utzig** [comment]
Thanks @SebastianBoe

**Pull request merged**
