### PR TITLE
Update pyocd calls to unified tool subcommands

### PR DESCRIPTION
**Pull request by MaureenHelm**
pyocd 0.14.0 merged its command-line tools into a unified pyocd tool
with subcommands. The separate command-line tools still remain, but are
deprecated. Update all pyocd calls in samples and documentation to use
the new unified pyocd tool with subcommands.

Note that pyocd 0.15.0 has an issue with the command 'pyocd erase',
which was fixed in pyocd 0.16.0.

Depends on zephyrproject-rtos/zephyr#13500

### CODE REVIEW

**Comment by utzig** [comment]
Funny fact, I have been using the FRDM-K64F a lot recently, and the only pyOCD that works well for me is 0.8.0, which unfortunately is Python2 only, but I tried a few recent versions and they all have some form of bug (SWD/JTAG issues, etc), which vary across releases but haven't found one that is actually usable/stable.

**Comment by MaureenHelm** [comment]
> Funny fact, I have been using the FRDM-K64F a lot recently, and the only pyOCD that works well for me is 0.8.0, which unfortunately is Python2 only, 

More recent versions of pyocd support python3.

> but I tried a few recent versions and they all have some form of bug (SWD/JTAG issues, etc), which vary across releases but haven't found one that is actually usable/stable.

Are you by any chance running pyocd in a virtual machine?

**Comment by utzig** [comment]
> Are you by any chance running pyocd in a virtual machine?

Linux native (no VMs of any kind).

**Comment by utzig** [comment]
Since the Zephyr PR was merge I am merging this one as well. Thanks!

**Pull request merged**
