### PR TITLE
Create ptest utility

### PR DESCRIPTION
**Pull request by d3zd3z**
This is a small utility that facilitates doing the Travis-style parallel tests during development. To use, `cd ptest`, and `cargo run`. It will read the configuration from the `.travis.yml` file.

### CODE REVIEW

**Comment by d3zd3z** [comment]
I wonder if I need a limit other than 8. I've got another change that cleans up the status display a bit.

**Comment by d3zd3z** [comment]
I was planning on defaulting to either the number of physical cores, or the number of threads, not sure which.

**Comment by utzig** [comment]
Wouldn't it be better to just squash these commits since it's all part of the first ptest release?

**Comment by d3zd3z** [comment]
Probably :-)

**Comment by d3zd3z** [comment]
All squashed.

**Comment by d3zd3z** [comment]
> Maybe it would be a good idea to remove the commented out code.
Do you mean the printlns in various points? Maybe I should add logging, and make them `debug!()`, which won't normally show up, but can be turned on.

**Comment by d3zd3z** [comment]
I can squash, if we think that is better, but I think review is easier before squashing.

**Comment by utzig** [comment]
Looks good!

**Pull request merged**
