### PR TITLE
boot: zephyr: Add check of RESETREAS for nRF SoC

### PR DESCRIPTION
**Pull request by jhn-nordic**
Only execute serial recovery if valid pin condition is detected
during power up reset or pin reset on nRF devices with RESETREAS
register. This is to prevent going into serial recovery when
waking up from power off mode with the same pin conditions that
is configured to trigger serial recovery.

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
> This is to prevent going into serial recovery when
waking up from power off mode with the same pin conditions that
is configured to trigger serial recovery.

How to trigger serial recovery for such a case?

**Comment by nvlsianpu** [comment]
@jhn-nordic ^^

**Comment by jhn-nordic** [comment]
> > This is to prevent going into serial recovery when
> > waking up from power off mode with the same pin conditions that
> > is configured to trigger serial recovery.
> 
> How to trigger serial recovery for such a case?

Power on reset or pin reset. 
(rr == 0 || (rr & NRF_POWER_RESETREAS_RESETPIN_MASK))

**Comment by nvlsianpu** [comment]
tested on regression - OK.

**Pull request merged**
