### PR TITLE
loader: Fix dependency check issue related to swap type

### PR DESCRIPTION
**Pull request by solsbarry**
Fix for issue #669

Signed-off-by: Barry Solomon barry.solomon@dexcom.com

### CODE REVIEW

**Comment by utzig** [comment]
> Fix for issue #669
> 
> Signed-off-by: Barry Solomon [barry.solomon@dexcom.com](mailto:barry.solomon@dexcom.com)

The commit doesn't seem to have a signed-off-by line, and it looks a bit weird with #669 twice.

**Comment by solsbarry** [comment]
i fixed the commit message

**Comment by utzig** [comment]
> i fixed the commit message

I believe the email must be inside `<>` symbols to pass the CI, let's see!

**Comment by utzig** [comment]
Thanks @solsbarry!

**Pull request merged**
